@startuml

    !include lexakai.theme
    
    title "com.telenav.cactus.metadata"
    
    BuildMetadata --> Map : "creates"
    class BuildMetadata
    {
        --(building)--
        +Map<String,String> buildProperties()
        +int currentBuildNumber()
        +BuildMetadata of(Class<?> projectType)
        --(collection)--
        +Map<String,String> projectProperties()
    }
    
    class BuildMetadataUpdater
    {
        --
        +void main(String[] arguments)
    }
    
    class BuildName
    {
        --
        +String current()
        --(naming)--
        +String name(int buildNumber)
    }
    
    enum BuildMetadata.Type
    {
        CURRENT
        PROJECT
    }
    
@enduml
